---
title: 'MB AtHome: LWL stimuli search'
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"

library(wordbankr)
library(childesr)
library(dplyr)
library(tidyr)
library(purrr)
library(stringi)

```


Goal of replacing at least part of the input entry in [Word Properties](https://docs.google.com/spreadsheets/d/1X_fSToEDGQ-jj03pY_xocKfT940LxmYPkoWkI4LDHRo/edit?usp=sharing) with this script.



```{r English_American}

# create overview of available measures
measures <- data.frame(matrix(NA, nrow=1, ncol=4))
names(measures) <- c("language", "Wordbank_AoA_understands", "Wordbank_AoA_produces", "CHILDES_token_freq")

# Wordbank
# first, identify the strings used for this language in wordbank
#Wordbank
# get_instruments()
wordbank_lang <- "English (American)"

# then, query Wordbank 
source("scripts/wordbank.R")
# returns aoa.m, a summary of youngest reported AoA for understanding and producing
# returns word_list, a list of the words in aoa.m to be used for querying chiles in the next step 

# CHILDES
# likely uses the collection names listed here: https://childes.talkbank.org/access/
# check by inputting function here: get_transcripts(collection = "Eng-NA")
childes_lang <- "Eng-NA"

# then, query childes
source("scripts/childes.R")
# returns prod_stats, a summary of the token frequency of the words in word_list


# Combine the Wordbank and CHILDES data together
# if CHILDES doesn't produce any data, then return just Wordbank data, with NA's in the CHILDES column

if(nrow(prod_stats) != 0){
d <- left_join(aoa.m, prod_stats, by = c("definition" = "gloss"))
} else{
  d <- aoa.m
  d$CHILDES_token_freq <- NA
}



# choose the top 8 and bottom 8 AoA words
# for each category
source("scripts/vocab_choice.R")


# write them into their own csv file
# which can be later edited to add additional information
vs_filename <- paste0(wordbank_lang, "_vocab_choice.csv")  

write.csv(vocab_sum, file = vs_filename)


```








